{
  "openapi": "3.0.0",
  "info": {
    "title": "FilesOnFly API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://{{base_url}}"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "tags": [
    {
      "name": "User"
    },
    {
      "name": "Storage"
    },
    {
      "name": "File"
    },
    {
      "name": "Pages"
    }
  ],
  "paths": {
    "/user/create": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "User Create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": ""
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "userId": 1
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "userId": null
                }
              }
            }
          }
        }
      }
    },
    "/storage/create": {
      "post": {
        "tags": [
          "Storage"
        ],
        "summary": "Storage Create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "user_id": 1,
                  "name": "Storage Name"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "storage_id": 1,
                  "storage_name": "Storage Name"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "storage_id": null
                }
              }
            }
          }
        }
      }
    },
    "/storage/delete": {
      "delete": {
        "tags": [
          "Storage"
        ],
        "summary": "Storage Delete",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": true,
                  "storage_id": 1
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": false
                }
              }
            }
          }
        }
      }
    },
    "/storage/{id}": {
      "get": {
        "tags": [
          "Storage"
        ],
        "summary": "Get Storage",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 123,
                  "name": "Storage Name",
                  "created_at": "20231306",
                  "status": "active",
                  "used_space_mb": 123
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": false,
                  "error": "Storage Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/storage/{id}/api-keys": {
      "get": {
        "tags": [
          "Storage"
        ],
        "summary": "API Keys",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 123,
                  "api_key": "APIKEYHERE",
                  "created_at": "20231306"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Storage"
        ],
        "summary": "Refresh API Keys",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "refresh": true
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "example-0": {
                    "summary": "API Keys Refreshed",
                    "value": {
                      "id": 123,
                      "api_key": "NEW_APIKEYHERE",
                      "refreshed": true,
                      "created_at": "20231306"
                    }
                  },
                  "example-1": {
                    "summary": "API Keys NOT Refreshed",
                    "value": {
                      "id": 123,
                      "api_key": "EXISTING_APIKEYHERE",
                      "refreshed": false,
                      "created_at": "20231306"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": false
                }
              }
            }
          }
        }
      }
    },
    "/file/{id}": {
      "get": {
        "tags": [
          "File"
        ],
        "summary": "Get File",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "_metadata": {
                    "file_name": "logo.png",
                    "path": "/static/files/",
                    "ext": ".png"
                  },
                  "id": 123,
                  "name": "Storage Name",
                  "created_at": "20231306",
                  "status": "active",
                  "used_space_mb": 123
                }
              }
            }
          }
        }
      }
    },
    "/file/search": {
      "get": {
        "tags": [
          "File"
        ],
        "summary": "Search File",
        "parameters": [
          {
            "name": "q",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "Query to search within file names"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "_metadata": {
                      "file_name": "logo.png",
                      "path": "/static/files/",
                      "ext": ".png"
                    },
                    "id": 123,
                    "name": "Storage Name",
                    "created_at": "20231306",
                    "status": "active",
                    "used_space_mb": 123
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/file/upload": {
      "put": {
        "tags": [
          "File"
        ],
        "summary": "File Upload",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "description": "File to upload",
                    "format": "binary"
                  },
                  "file_name": {
                    "type": "string",
                    "description": "e.g. logo.png"
                  },
                  "file_path": {
                    "type": "string",
                    "description": "e.g. /static/files/"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": false
                }
              }
            }
          },
          "undefined": {
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\r\n    \"status\": true,\r\n    \"file_id\": 1,\r\n    \"file_name\": \"logo.png\",\r\n    \"file_ext\": \".png\",\r\n    \"created_at\": \"2024-03-15T12:34:56Z\",\r\n    \"updated_at\": \"2024-03-15T12:34:56Z\"\r\n}"
              }
            }
          }
        }
      }
    },
    "/file/delete": {
      "delete": {
        "tags": [
          "File"
        ],
        "summary": "File Delete",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": true,
                  "storage_id": 1
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": false
                }
              }
            }
          }
        }
      }
    },
    "/page/dashboard": {
      "get": {
        "tags": [
          "Pages"
        ],
        "summary": "Dashboard",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": true,
                  "stats": {
                    "total_used_mb": 1024,
                    "max_total_used_mb": 30000,
                    "total_file_count": 1436,
                    "throughput_limit": 256
                  },
                  "storages": [
                    {
                      "id": 123,
                      "name": "Storage Name",
                      "created_at": "20231306",
                      "status": "active",
                      "used_space_mb": 123
                    }
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": false
                }
              }
            }
          }
        }
      }
    }
  }
}